#!/bin/sh
set -eux

export COMPOSER_HOME=/app/.composer
export PATH=$PATH:/app/vendor/bin
export TEMP=/app/.dockerweb/tmp
export TERM=xterm
export PS1='\u@\H:\w\$ '
export npm_config_cache=/app/.dockerweb/npm-cache
alias art='php artisan'
alias ll='ls -alh'

mkdir -p /app/public
mkdir -p /app/.dockerweb
chown -R www-data:www-data /app

if [ ! -z "${SSH_PASSWORD:+x}" ]; then
	echo "www-data:${SSH_PASSWORD}" | chpasswd
	exec dropbear -FeEwgjk -p 22 -K 30 -I 600
	exit 0
fi

# TODO: service sendmail restart

if [ "$1" = "php-fpm" ]; then
	shift
	exec php-fpm "$@"
	exit 0
fi

sleep ${SLEEP:-0}

# exec "$@"
su -l -s /bin/bash -c "cd /app; $*" www-data
