version: '3.5'

networks:
  proxy:
    external: true

services:
  web:
    image: fffaraz/php
    restart: always
    depends_on:
      - postgres
      - mariadb
      - redis
    volumes:
      - ./app:/app
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mywebsite-http.entrypoints=http"
      - "traefik.http.routers.mywebsite-http.rule=Host(`mywebsite.example.com`)"
      - "traefik.http.routers.mywebsite-http.middlewares=https-redirect@file"
      - "traefik.http.routers.mywebsite-secure.entrypoints=https"
      - "traefik.http.routers.mywebsite-secure.rule=Host(`mywebsite.example.com`)"
      - "traefik.http.routers.mywebsite-secure.tls=true"
      - "traefik.http.routers.mywebsite-secure.tls.certresolver=http"
      - "traefik.http.routers.mywebsite-secure.service=mywebsite"
      - "traefik.http.services.mywebsite.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  postgres:
    image: postgres:12.2 # https://hub.docker.com/_/postgres
    restart: always
    env_file: .env
    shm_size: 4G
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql.conf:ro

  redis:
    image: redis:latest # https://hub.docker.com/_/redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"] # "--auto-aof-rewrite-min-size", "8mb"
    logging:
      driver: "none"
    volumes:
      - ./volumes/redis:/data

  mariadb:
    image: mariadb:10.4 # https://hub.docker.com/_/mariadb/
    restart: always
    env_file: .env
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-log:/var/log/mysql
