#!/bin/sh
set -e

export COMPOSER_HOME=/app/.composer
export PATH=$PATH:/app/vendor/bin
export TEMP=/app/.dockerweb/tmp
export TERM=xterm
export PS1='\u@\H:\w\$ '
export npm_config_cache=/app/.dockerweb/npm-cache
alias art='php artisan'
alias ll='ls -alh'

mkdir -p /app/public
chown -R www-data:www-data /app

# service sendmail restart

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
