version: '3'

services:
  app:
    image: fffaraz/php:latest
    restart: always
    volumes:
      - ./app:/app
      - ./socket:/socket
      - mariadb:/db

  dufs:
    image: sigoden/dufs:latest
    restart: always
    command: --bind /socket/dufs.sock --allow-all /app
    volumes:
      - ./app:/app
      - ./socket:/socket

volumes:
  mariadb:
    external: true
