version: '3'

networks:
  dbnet:
    external: true

services:
  app:
    image: fffaraz/php # https://hub.docker.com/r/fffaraz/php
    restart: always
    networks:
      - default
      - dbnet
    volumes:
      - ./app:/app
      - ./volumes/socket:/socket
